language: node_js
sudo: false

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Secure environment variable
  keep-history: true
  on:
    branch: gh-pages


before_script:
  - npm install -g gulp
script: gulp test
