language: node_js
sudo: false

node_js:
  - "stable"
cache:
  directories:
  - node_modules
  
before_script:
  - cd dev && npm install
script: 
  - npm run gulp

branches:
  only:
  - development

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Secure environment variable
  keep-history: true
  local_dir: build
  on:
    branch: gh-pages
